### PR TITLE
Domains support.

### PR DESCRIPTION
**Pull request by vartagg**
Hello.
I added domains support. And written tests for this functionality. I think it would be helpful - to manipulate domains/subdomains of URLs.

### CODE REVIEW

**Comment by agriffis** [comment]
Thanks for the PR! Could you elaborate on the use-cases for these operations?

**Comment by vartagg** [comment]
@agriffis Of course :) Sometimes may be need to change domain or subdomain of the URL. For example, for creating a direct link to video/audio. Suppose we have a URL "http://example.com/video/12345678", and we need to transform this to the direct link to the video: "http://video.example.com/file/12345678". With domains support, we can get this by this way:
`url = URLObject('http://example.com/video/12345678')`
`direct_link = url.add_subdomain('video').with_path('file').add_path(url.path.segments[-1])`
Another use-cases: if we simply need to get subdomain of current url:
`URLObject(url).subdomain`
Or change high-level domain:
`In: url.with_domain('org', -1)`
`Out: URLObject(u'http://example.org/video/12345678')`

**Comment by vartagg** [comment]
Oh, "high-level" domains are correctly named as "top-level". I'll refactor this wrong name.

**Comment by agriffis** [comment]
@vartagg Thanks for the explanation. I'm not inclined to pull this as-is.

1. It makes some invalid assumptions about what different parts of the hostname string are called. For example, it falls apart with international TLDs.
2. It doesn't sit very well with the rest of the `URLObject` API. I think it would need to be implemented differently, probably something like `URLPath` is done.
3. In any case, I'm uncertain that it passes the sufficiently-generally-useful test. The most common operations with hostname/domain are covered by `.hostname` (extract) and `.with_hostname()` (replace). The operations you describe seem either specialized to your application, or trivial to implement using the existing API along with string operations.

**Comment by vartagg** [comment]
@agriffis 

>It makes some invalid assumptions about what different parts of the hostname string are called. For example, it falls apart with international TLDs.

Please, give me an example of invalid assumption and fail with international TLDs. If use unicode characters in domain name, all is working properly, I didn't find any problems. 

`In: url = URLObject(u'http://красноярск.рф')`
`In: print url`
http://красноярск.рф
`In: url2 = url.add_subdomain(u'музеи')`
`In: print url2`
http://музеи.красноярск.рф

Maybe you about "idna" coding? I thought about it and can realize mechanisms for transformation international domain names to IDNA format.  Then the question that needed to resolve - what to use by default.  But this is a solvable problem.


>It doesn't sit very well with the rest of the URLObject API. I think it would need to be implemented differently, probably something like URLPath is done.

Maybe, maybe... I tried as best as possible to integrate it into an existing API. If you want, you can help me to improve it. 

>In any case, I'm uncertain that it passes the sufficiently-generally-useful test. The most common operations with hostname/domain are covered by .hostname (extract) and .with_hostname() (replace). The operations you describe seem either specialized to your application, or trivial to implement using the existing API along with string operations.

I think it may not necessarily be useful only for my application. Manipulations with domains / subdomains are not so rare when constructing URLs. Not so frequently as qs or paths changes, but it happens :-)
Yes, this can be done with string operations, but this is a workaround. With the same success can be built all URL components, but this is often inconvenient. Domain manipulations API make the code at least more readable, imho.

**Comment by agriffis** [comment]
> Please, give me an example of invalid assumption and fail with international TLDs.

Sorry, I didn't mean to be vague. I was referring to (for example) `.co.uk` in which case `.get_domain()` would return `"co"`.

I'm not entirely against an API for hostname manipulation, but I need to think about it for a bit...

**Comment by vartagg** [comment]
@agriffis 
".co.uk" is a nice example when calling `get_domain()` returns non-obvious result. At this moment, I don't know, how to programmatically auto-avoid this situation. Perhaps, the programmer should know in advance what kind of domains he works with, and must forcibly specify the correct argument. Another way to resolve this - create a "list of special cases", but it may cause to even more non-obvious results.   
This is the problem, I agree with you. 

One way: I can rename `DOMAIN_LEVEL_BASE` to `DOMAIN_LEVEL_SECOND`. Then it will be correct. In many sources, such as wikipedia, this term is called just that - "a second-level domain". I can also define `DOMAIN_LEVEL_THIRD = -3` by analogy, for better ease of use API for ".co.uk"-like things.

**Comment by vartagg** [comment]
After some googling I found that terms I used in API are incorrect.
This applies to "domains", "subdomains", etc. So, I decline this PR, and I'm going to create another one with correct names.

@agriffis  What do you think, maybe opt out of the term "domain", because it is recursive, and is unlikely to be able to help us?  Maybe it would be better to make the ability to change the left and right part only, if we consider the hostname splitted by '.'?

**Comment by vartagg** [comment]
I found correct terms:
>A domain name consists of one or more parts, technically called labels, that are conventionally concatenated, and delimited by dots, such as example.com.

http://en.wikipedia.org/wiki/Domain_name#Domain_name_syntax
And "domain" is matches to a "hostname", but is considered in the context of DNS system. http://support.suso.com/supki/What_is_the_difference_between_a_hostname_and_a_domain_name
The use of domains themselves in `URLObject` doesn't make sense. But `domain_labels` - probably, make sense :-)

**Comment by zacharyvoase** [comment]
I'm not certain we need this. Subdomain manipulation is rare enough and when it does need to happen, it should be feasible with built-in Python features (you're just doing `with_hostname('.'.join(modify(hostname.split('.'))))`). I'm interested in exploring some Lens-like concepts for easily modifying immutable URLs in future though.

**Comment by agriffis** [comment]
I'm in agreement with @zacharyvoase. Thanks anyway for the discussion @vartagg.

**Comment by vartagg** [comment]
As you wish.

**Pull request closed without merging**
